//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace epyenv.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.8.1.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://www.python.org/ftp/python/")]
        public string PythonURL {
            get {
                return ((string)(this["PythonURL"]));
            }
            set {
                this["PythonURL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://bootstrap.pypa.io/get-pip.py")]
        public string GetPipURL {
            get {
                return ((string)(this["GetPipURL"]));
            }
            set {
                this["GetPipURL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("get-pip.py")]
        public string GetPipName {
            get {
                return ((string)(this["GetPipName"]));
            }
            set {
                this["GetPipName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("tkinter3.5.X_Amd64.zip")]
        public string tkinter3_5_Amd64 {
            get {
                return ((string)(this["tkinter3_5_Amd64"]));
            }
            set {
                this["tkinter3_5_Amd64"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("tkinter3.6.X_Amd64.zip")]
        public string tkinter3_6_Amd64 {
            get {
                return ((string)(this["tkinter3_6_Amd64"]));
            }
            set {
                this["tkinter3_6_Amd64"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("tkinter3.7.X_Amd64.zip")]
        public string tkinter3_7_Amd64 {
            get {
                return ((string)(this["tkinter3_7_Amd64"]));
            }
            set {
                this["tkinter3_7_Amd64"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("tkinter3.8.X_Amd64.zip")]
        public string tkinter3_8_Amd64 {
            get {
                return ((string)(this["tkinter3_8_Amd64"]));
            }
            set {
                this["tkinter3_8_Amd64"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("tkinter3.9.X_Amd64.zip")]
        public string tkinter3_9_Amd64 {
            get {
                return ((string)(this["tkinter3_9_Amd64"]));
            }
            set {
                this["tkinter3_9_Amd64"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("tkinter3.5.X_Win32.zip")]
        public string tkinter3_5_Win32 {
            get {
                return ((string)(this["tkinter3_5_Win32"]));
            }
            set {
                this["tkinter3_5_Win32"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("tkinter3.6.X_Win32.zip")]
        public string tkinter3_6_Win32 {
            get {
                return ((string)(this["tkinter3_6_Win32"]));
            }
            set {
                this["tkinter3_6_Win32"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("tkinter3.7.X_Win32.zip")]
        public string tkinter3_7_Win32 {
            get {
                return ((string)(this["tkinter3_7_Win32"]));
            }
            set {
                this["tkinter3_7_Win32"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("tkinter3.8.X_Win32.zip")]
        public string tkinter3_8_Win32 {
            get {
                return ((string)(this["tkinter3_8_Win32"]));
            }
            set {
                this["tkinter3_8_Win32"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("tkinter3.9.X_Win32.zip")]
        public string tkinter3_9_Win32 {
            get {
                return ((string)(this["tkinter3_9_Win32"]));
            }
            set {
                this["tkinter3_9_Win32"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("amd64")]
        public string ArchAmd64 {
            get {
                return ((string)(this["ArchAmd64"]));
            }
            set {
                this["ArchAmd64"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("win32")]
        public string ArchWin32 {
            get {
                return ((string)(this["ArchWin32"]));
            }
            set {
                this["ArchWin32"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("python-{0}-embed-{1}.zip")]
        public string PythonEmbedName {
            get {
                return ((string)(this["PythonEmbedName"]));
            }
            set {
                this["PythonEmbedName"] = value;
            }
        }
    }
}
